insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (1, '2022-08-19', 'Ready for dispatch', 'within 3 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (4, '2022-10-17', 'Pending', 'within 4 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (12, '2022-12-03', 'In process', 'within 5 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (6, '2022-09-10', 'In process', 'within 4 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (9, '2022-04-05', 'Delivered', 'within 1 day');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (11, '2022-04-20', 'Pending', 'within 4 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (15, '2023-02-24', 'In process', 'within 5 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (10, '2022-04-11', 'In process', 'within 3 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (8, '2022-09-24', 'Delivered', 'within 3 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (16, '2022-10-28', 'In process', 'within 4 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (3, '2023-03-14', 'In process', 'within 3 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (1, '2022-11-08', 'Dispatched', 'within 2 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (3, '2022-03-17', 'Dispatched', 'within 5 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (3, '2022-06-26', 'Pending', 'within 5 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (2, '2022-04-05', 'Ready for dispatch', 'within 3 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (8, '2022-06-09', 'In process', 'within 2 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (2, '2022-12-08', 'Pending', 'within 5 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (9, '2022-12-14', 'Dispatched', 'within 3 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (16, '2022-11-11', 'Dispatched', 'within 2 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (9, '2022-10-11', 'Ready for dispatch', 'within 3 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (8, '2022-09-15', 'Ready for dispatch', 'within 1 day');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (11, '2022-07-12', 'Dispatched', 'within 4 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (14, '2023-02-02', 'Pending', 'within 3 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (5, '2022-07-17', 'Pending', 'within 2 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (10, '2022-11-21', 'Delivered', 'within 3 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (6, '2022-11-04', 'Dispatched', 'within 2 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (4, '2022-03-21', 'Ready for dispatch', 'within 4 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (7, '2022-06-13', 'Pending', 'within 2 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (2, '2022-06-21', 'In process', 'within 1 day');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (13, '2022-04-11', 'Ready for dispatch', 'within 4 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (14, '2022-05-04', 'Ready for dispatch', 'within 5 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (15, '2022-07-02', 'Delivered', 'within 2 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (17, '2022-07-08', 'Ready for dispatch', 'within 1 day');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (2, '2022-07-26', 'Ready for dispatch', 'within 1 day');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (6, '2022-11-11', 'Pending', 'within 2 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (15, '2023-01-22', 'Dispatched', 'within 1 day');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (15, '2022-11-09', 'Delivered', 'within 5 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (16, '2022-10-21', 'Ready for dispatch', 'within 2 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (17, '2022-12-01', 'Ready for dispatch', 'within 5 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (7, '2022-11-15', 'Dispatched', 'within 1 day');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (12, '2022-06-14', 'Dispatched', 'within 3 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (9, '2022-05-29', 'In process', 'within 2 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (17, '2022-07-10', 'Delivered', 'within 2 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (3, '2022-12-11', 'Pending', 'within 5 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (10, '2022-09-23', 'Dispatched', 'within 3 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (4, '2022-10-13', 'In process', 'within 4 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (2, '2022-08-24', 'Pending', 'within 5 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (11, '2022-08-29', 'Pending', 'within 1 day');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (10, '2022-10-20', 'Ready for dispatch', 'within 4 days');
insert into DB_Assignment.Orders  (UserID, OrderDate, OrderStatus, OrderExpectedDeliveryDate) values (17, '2022-05-23', 'Dispatched', 'within 5 days');
